#################################################
#
#  Improvements and feedback are welcome
#
#  This file is released under GPL >= 2
#
#################################################

install( FILES tde_update_config.desktop DESTINATION ${AUTOSTART_INSTALL_DIR} )
install( PROGRAMS tde_update_config DESTINATION ${BIN_INSTALL_DIR} )
