# List generated with ls -1 *.desktop | sed -e 's/^/\t\t/;s/$/ \\/'
services_DATA = \
		academic_en.desktop \
		academic_ru.desktop \
		amg.desktop \
		archpkg.desktop \
		archwiki.desktop \
		arxiv.desktop \
		ask.desktop \
		aur.desktop \
		baidu.desktop \
		bing.desktop \
		brave.desktop \
		bugft.desktop \
		bugno.desktop \
		chatgpt.desktop \
		citeseer.desktop \
		codeberg.desktop \
		cpan.desktop \
		cppreference.desktop \
		ctan.desktop \
		ctan_file.desktop \
		curlie.desktop \
		dbug.desktop \
		de2en.desktop \
		de2fr.desktop \
		deb.desktop \
		devuanpkg.desktop \
		docbook.desktop \
		doi.desktop \
		duckduckgo.desktop \
		duckduckgo_html.desktop \
		duckduckgo_lite.desktop \
		ecosia.desktop \
		en2de.desktop \
		en2es.desktop \
		en2fr.desktop \
		en2it.desktop \
		es2en.desktop \
		excite.desktop \
		foldoc.desktop \
		fr2de.desktop \
		fr2en.desktop \
		fsd.desktop \
		gentoopkg.desktop \
		gentoowiki.desktop \
		github.desktop \
		gnudb.desktop \
		google_advanced.desktop \
		google.desktop \
		google_images.desktop \
		google_lucky.desktop \
		google_maps.desktop \
		google_movie.desktop \
		google_news.desktop \
		google_scholar.desktop \
		grec.desktop \
		hyperdictionary.desktop \
		imdb.desktop \
		it2en.desktop \
		jstor.desktop \
		kde_store.desktop \
		leo.desktop \
		linuxquestions.desktop \
		lycos.desktop \
		mdn.desktop \
		metacrawler.desktop \
		msdn.desktop \
		mw.desktop \
		mw_thesaurus.desktop \
		openstreetmap.desktop \
		pexels.desktop \
		pgpkeys.desktop \
		php.desktop \
		pixabay_images.desktop \
		pixabay_music.desktop \
		pixabay_sfx.desktop \
		pixabay_videos.desktop \
		pkgs-org.desktop \
		pling.desktop \
		python2.desktop \
		python3.desktop \
		qt3.desktop \
		qt4.desktop \
		qt5.desktop \
		qt6.desktop \
		qwant.desktop \
		rae.desktop \
		rfc.desktop \
		rpmfind.desktop \
		slackpkg.desktop \
		sourceforge.desktop \
		srht.desktop \
		startpage.desktop \
		tdeapidocs.desktop \
		tdegw.desktop \
		tdewiki.desktop \
		tmdb.desktop \
		tqt.desktop \
		trinity_look.desktop \
		urbandic.desktop \
		wiby.desktop \
		wikimedia_commons.desktop \
		wikipedia_de.desktop \
		wikipedia_el.desktop \
		wikipedia_en.desktop \
		wikipedia_es.desktop \
		wikipedia_fr.desktop \
		wikipedia_it.desktop \
		wikipedia_ja.desktop \
		wikipedia_pl.desktop \
		wikipedia_ru.desktop \
		wikipedia_zh.desktop \
		wiktionary_de.desktop \
		wiktionary_el.desktop \
		wiktionary_en.desktop \
		wiktionary_es.desktop \
		wiktionary_fr.desktop \
		wiktionary_it.desktop \
		wiktionary_ja.desktop \
		wiktionary_pl.desktop \
		wiktionary_ru.desktop \
		wiktionary_zh.desktop \
		wordref.desktop \
		wordref_synonyms.desktop \
		yahoo.desktop \
		yandex.desktop

servicesdir = $(kde_servicesdir)/searchproviders
